const API = location.hostname === 'localhost' || location.hostname === '127.0.0.1' ? 'http://127.0.0.1:8000' : '';
const demoKey='bullstreet_demo_portfolio';
async function api(path, opt){ if(API) return fetch(API+path,opt).then(r=>r.json()); throw new Error('static'); }
function localData(){return JSON.parse(localStorage.getItem(demoKey)||'[]')}function saveLocal(d){localStorage.setItem(demoKey,JSON.stringify(d))}
async function addHolding(){const h={symbol:symbol.value.trim().toUpperCase(),name:name.value,market:market.value,shares:+shares.value,avg_cost:+avg.value}; if(!h.symbol||!h.shares||!h.avg_cost)return alert('請輸入代號、股數、均價'); try{await api('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(h)})}catch{const d=localData();d.push(h);saveLocal(d)} refreshAll()}
async function deleteHolding(i){try{await api('/api/portfolio/'+i,{method:'DELETE'})}catch{const d=localData();d.splice(i,1);saveLocal(d)} refreshAll()}
async function getHoldings(){try{return await api('/api/portfolio')}catch{return localData()}}
async function refreshAll(){const data=await getHoldings(); holdings.innerHTML=data.map((h,i)=>`<div class="holding"><div><b>${h.symbol}</b> ${h.name||''}<div class="muted">${h.market}｜${h.shares} 股｜成本 ${h.avg_cost}</div></div><button onclick="analyze('${h.symbol}','${h.market}')">分析</button><button onclick="deleteHolding(${i})">刪除</button></div>`).join('')||'<p class="muted">先新增一筆持股。</p>'; totalValue.textContent='$ '+Math.round(data.reduce((s,h)=>s+h.shares*h.avg_cost,0)).toLocaleString(); loadMarket(); if(data[0]) analyze(data[0].symbol,data[0].market)}
async function analyze(sym,mkt){analysis.innerHTML='<p class="muted">分析中...</p>';try{const a=await api(`/api/analyze/${sym}?market=${mkt}`);analysis.innerHTML=`<div class="mini"><h3>${a.symbol} 技術面</h3><p class="scoreline">分數：<b>${a.technical_score}</b>/100</p><p>${a.technical_view}</p><p class="muted">Price ${a.quote.price}｜MA20 ${a.quote.ma20}｜MA60 ${a.quote.ma60}｜20日 ${a.quote.ret20}%</p></div><div class="mini"><h3>相關概念</h3>${a.concepts.map(x=>`<span class="tag">${x}</span>`).join('')||'--'}<h3>相關股票</h3>${a.related_stocks.map(x=>`<span class="tag">${x}</span>`).join('')||'--'}</div><div class="mini"><h3>大盤/美股影響</h3>${a.macro_links.map(x=>`<p>• ${x}</p>`).join('')}</div><div class="mini"><h3>待串資料</h3>${a.todo_data.map(x=>`<p>• ${x}</p>`).join('')}</div>`}catch(e){analysis.innerHTML='<p class="muted">GitHub Pages 靜態模式不能直接打後端；請本機啟動 FastAPI，或把後端部署到 Render/Railway 後設定 API URL。</p>'}}
let chart;async function loadMarket(){try{const m=await api('/api/market');const labels=Object.keys(m);const vals=labels.map(k=>m[k]?.ret20||0);marketText.textContent=labels.map(k=>`${k}: ${m[k]?.ret20??'--'}%`).join(' / ');const ctx=document.getElementById('marketChart'); if(chart)chart.destroy(); chart=new Chart(ctx,{type:'bar',data:{labels,datasets:[{label:'20日漲跌幅 %',data:vals}]},options:{plugins:{legend:{labels:{color:'#eafff1'}}},scales:{x:{ticks:{color:'#9ab8a7'}},y:{ticks:{color:'#9ab8a7'}}}})}catch{marketText.textContent='靜態 Demo 模式：啟動後端後可顯示 NASDAQ / SOX / S&P500 / 加權指數。'}}refreshAll();
